---
version: '2'
services:
  postgres:
    image: postgres:9.5
    restart: always
    environment:
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=gogs"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - gogs
  gogs:
    image: gogs/gogs:0.12
    restart: always
    ports:
      - "10022:22"
      - "3000:3000"
    links:
      - postgres
    environment:
      - "RUN_CROND=true"
    networks:
      - gogs
    volumes:
      - "gogs-data:/data"
    depends_on:
      - postgres

networks:
  gogs:

volumes:
  db-data:
  gogs-data: