---
id: a97ab29a-dec7-4f46-804f-25db92bb7259
name: Gogs
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: The Gogs project aims to build a simple, stable and extensible self-hosted Git service that can be set up 
  in the most painless way. With Go, this can be done with an independent binary distribution across all platforms that 
  Go supports, including Linux, macOS, Windows and ARM-based systems.
shortDescription: The Gogs project aims to build a simple, stable and extensible self-hosted Git service that can be set
  up in the most painless way.
coverImageFilename: gogs.png
serviceCategoryName: Git
version:
  id: b4d3f7bb-9964-4448-901c-2558f4750456
  version: '0.12'
  serviceOptionCategories: []
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yml
    dotEnvFile: ''
    envFilenames: []
