---
id: 8acfc095-2df7-4c49-b7de-ad805dfd0a7c
name: Kubernetes Examples
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: |
  Kubernetes is an open-source container orchestration system for automating 
  software deployment, scaling, and management. Originally designed by Google, the project
  is now maintained by the Cloud Native Computing Foundation.
  This service offering demonstrates the SLM abilities to deploy on Kubernetes container orchestration systems.
shortDescription: This service offering demonstrates the SLM abilities to deploy on Kubernetes container orchestration systems.
coverImageFilename: thumbnail.png
serviceCategoryName: Application
version:
  id: 82c278c8-2c75-45d9-b544-0d83596b15e3
  version: 1.0.0
  serviceOptionCategories:
    - id: 0
      name: Environment Options
      serviceOptions:
        - relation: 'kubernetes-so-demo|hello-app-server'
          key: DEMO_GREETING
          name: Greeting (demo env var)
          description: This specifies the greeting demo variable.
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'Hello from the environment'
          valueType: STRING
          required: true
          editable: true
        - relation: 'kubernetes-so-demo|hello-app-server'
          key: DEMO_FAREWELL
          name: Farewell (demo env var)
          description: This specifies the farewll demo variable.
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'Such a sweet sorrow'
          valueType: STRING
          required: true
          editable: true
        - relation: '$'
          key: ${{deployment_image_tag}}
          name: Image tag (string replace) for the deployment
          description: This specifies the image tag used for the container.
          optionType: STRING_REPLACE
          defaultValue: 'gcr.io/google-samples/node-hello:1.0'
          valueType: STRING
          required: true
          editable: true
        - relation: '$'
          key: ${{crd_image_tag}}
          name: Image tag (string replace) for the crd
          description: This specifies the image tag used for the container.
          optionType: STRING_REPLACE
          defaultValue: 'gcr.io/google-samples/node-hello:1.0'
          valueType: STRING
          required: true
          editable: true
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: KUBERNETES
    manifestFilename: manifest.yaml
