version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.4.0
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password
      - SUDO_PASSWORD=password
      - DEFAULT_WORKSPACE=/config/workspace
    ports:
      - 8443:8443
    restart: always
