---
id: 457b7d70-108e-466c-8cff-4321b7629639
name: Visual Studio Code Server
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: Visual Studio Code ist ein kostenloser Quelltext-Editor von Microsoft. Visual Studio Code ist 
  plattformübergreifend für die Betriebssysteme Windows, macOS und Linux verfügbar. Visual Studio Code basiert auf dem 
  Framework Electron und ermöglicht u. a. Syntaxhervorhebung, Code-Faltung, Debugging, Autovervollständigung und 
  Versionsverwaltung.
shortDescription: Code-server is VS Code running on a remote server, accessible through the browser.
coverImageFilename: code.png
serviceCategoryName: IDE
version:
  id: d4d6507c-4c5d-4bff-aa9e-a9c9af7907f3
  version: 4.4.0
  serviceOptionCategories: []
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yml
    dotEnvFile: ''
    envFilenames: []
