version: '3'
services:
  compaile-ui:
    build: ./compaile-ui
    container_name: compaile-ui
    image: gitlab.git-ai.de:5050/leo/fabos-compaile-2023/compaile-ui:full
    ports:
      - "9080:80"
    volumes:
      - app-volume:/usr/data

  compaile-backend:
    build: ./compaile-backend
    container_name: compaile-backend
    image: gitlab.git-ai.de:5050/leo/fabos-compaile-2023/compaile-backend:latest
    volumes:
      - app-volume:/usr/data
    ports:
      - "9203:9203"
      - "9204:9204"
    restart: on-failure
    environment:
      DUMMY_ENV: "dummy_value"
volumes:
  app-volume:
