version: "3.9"

services:
  stream-viewer:
    image: fabos4ai/mjpeg-stream-viewer:latest
    ports:
      - "20080:80"
    environment:
      VUE_APP_AAS_REGISTRY: http://localhost:4000/registry
      VUE_APP_AAS_ID: CameraAASId
