version: "3.9"

services:
  stream-viewer:
    image: fabos4ai/mjpeg-stream-viewer:0.0.2
    ports:
      - "20080:80"
    environment:
      VUE_APP_AAS_REGISTRY: http://localhost:8082/aas/shell-registry
      VUE_APP_SUBMODEL_REGISTRY: http://localhost:8083/aas/submodel-registry
      VUE_APP_AAS_ID: Resource_67c5591a-6c0b-4b48-96c4-ee1b47332a31
