---
id: 5fe39eb1-0fb8-4b3f-96cd-22a65d41c085
name: Camera Stream Viewer
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: This camera stream viewer can be configured to dislay an MJPEG camera stream embedded in an web application.
  Therefore the application pulls the stream URL from a camera AAS on an AAS server. 
  Hence, the AAS server host path and AAS ID has to be specified during deployment, via environement variables.
shortDescription: This stream viewer can be configured to display an MJPEG camera stream embedded in an web application.
coverImageFilename: icon.png
serviceCategoryName: Dashboard
version:
  id: c1e0f45a-0f33-4deb-96f4-5979e8e14fe7
  version: 0.0.2
  serviceOptionCategories:
    - id: 0
      name: Environment Options
      serviceOptions:
        - relation: 'stream-viewer'
          key: VUE_APP_AAS_REGISTRY
          name: AAS Registry
          description: 'Specifies the url of the AAS registry.'
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'AAS_REGISTRY'
          valueType: SYSTEM_VARIABLE
          required: false
          editable: false
        - relation: 'stream-viewer'
          key: VUE_APP_SUBMODEL_REGISTRY
          name: Submodel Registry
          description: 'Specifies the url of the Submodel registry.'
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'SUBMODEL_REGISTRY'
          valueType: SYSTEM_VARIABLE
          required: false
          editable: false
        - relation: 'stream-viewer'
          key: VUE_APP_AAS_ID
          name: Camera
          description: 'Specifies the AAS ID of the camera to connect to.'
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'Resource_67c5591a-6c0b-4b48-96c4-ee1b47332a31'
          valueType: AAS_SM_TEMPLATE
          required: true
          editable: true
  serviceRequirements:
    - name: OSRequirement
      logics:
        - type: ALL
          properties:
            - name: HostOSArchitecture
              semanticId: 0173-1#02-BAB457#005
              value: x86_64
              parentSubmodelsSemanticIds: [https://eclipse.dev/slm/aas/sm/PlatformResources]
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yaml
    dotEnvFile: ''
    envFilenames: []
