---
version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge