---
id: 68b0b61a-148b-4602-a2b6-8124df0e169e
name: RabbitMQ
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: RabbitMQ is open source message broker software (sometimes called message-oriented middleware) that 
  implements the Advanced Message Queuing Protocol (AMQP). The RabbitMQ server is written in the Erlang programming 
  language and is built on the Open Telecom Platform framework for clustering and failover. Client libraries to 
  interface with the broker are available for all major programming languages.
shortDescription: RabbitMQ is open source message broker software (sometimes called message-oriented middleware) that 
  implements the Advanced Message Queuing Protocol (AMQP).
coverImageFilename: rabbitmq.png
serviceCategoryName: Broker
version:
  id: fc2b2d69-d07e-4450-ab3c-2f1b794cecda
  version: '3.10'
  serviceOptionCategories:
    - id: 0
      name: Environment
      serviceOptions:
        - relation: ''
          key: RABBITMQ_DEFAULT_USER
          name: Default Username
          description: This name is used for the default user
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'user'
          valueType: STRING
          required: true
          editable: true
        - relation: ''
          key: RABBITMQ_DEFAULT_PASS
          name: Default Password
          description: Password for default user
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'password'
          valueType: PASSWORD
          required: true
          editable: true
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yml
    dotEnvFile: ''
    envFilenames: []
