version: '3'

services:
  aas-registry:
    image: eclipsebasyx/aas-registry:1.3.1
    restart: always
    depends_on:
      - aas-database
    networks:
      default:
        aliases:
          - aas-registry
    ports:
      - "4000:4000"
