---
id: 74d29e30-2ad6-46ce-9952-b11744a82cea
name: NodeRed
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: Node-RED ist ein von IBM entwickeltes grafisches Entwicklungswerkzeug. Die Software ermöglicht es, 
  Anwendungsfälle im Bereich des Internets der Dinge mit einem einfachen Baukastenprinzip umzusetzen. Die einzelnen 
  Funktionsbausteine werden durch Ziehen von Verbindungen verbunden. Eine große Auswahl an mitgelieferten Bausteinen
  deckt die meisten der gängigsten Dienste und Technologien ab.
shortDescription: Node-RED ist ein grafisches Entwicklungswerkzeug
coverImageFilename: node-red.png
serviceCategoryName: Middleware
version:
  id: 6c73cb6f-1712-4a2e-a46a-b1d07c7d8ee8
  version: 2.2.2
  serviceOptionCategories: []
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yml
    dotEnvFile: ''
    envFilenames: []
