version: '3'

services:
  aas-server:
    image: eclipsebasyx/aas-server:1.3.1
    restart: always
    depends_on:
      - aas-database
    networks:
      default:
        aliases:
          - aas-server
    ports:
      - "4001:4001"

  aas-database:
    image: mongo:latest
    restart: always
    networks:
      default:
        aliases:
          - aas-database
    volumes:
      - "aas_database:/data/db"

volumes:
  aas_database: