version: '3.4'

services:
  grafana:
    image: grafana/grafana:8.5.3
    container_name: grafana
    # https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
    # https://grafana.com/docs/grafana/latest/auth/ldap/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=true
      - GF_AUTH_LDAP_ENABLED=false
      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning/
    ports:
      - "3000:3000"

