---
id: 6e558e14-47a9-426a-8b51-2f5d7e2331ed
name: Grafana
serviceVendorId: dac52253-a580-479a-84fe-2ca0ae90fb2c
description: Grafana is a multi-platform open source analytics and interactive visualization web application. It 
  provides charts, graphs, and alerts for the web when connected to supported data sources. A licensed Grafana 
  Enterprise version with additional capabilities is also available as a self-hosted installation or an account on the
  Grafana Labs cloud service. It is expandable through a plug-in system. End users can create complex monitoring 
  dashboards using interactive query builders. Grafana is divided into a front end and back end, written in TypeScript 
  and Go, respectively.
shortDescription: Grafana is a multi-platform open source analytics and interactive visualization web application.
coverImageFilename: grafana.png
serviceCategoryName: Dashboard
version:
  id: 1ce1a296-bfde-4f15-9439-921fed6409a2
  version: 8.5.3
  serviceOptionCategories:
    - id: 0
      name: Environment
      serviceOptions:
        - relation: ''
          key: GF_SECURITY_ADMIN_USER
          name: Admin Username
          description: This name is used for the admin user
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'admin'
          valueType: STRING
          required: true
          editable: true
        - relation: ''
          key: GF_SECURITY_ADMIN_PASSWORD
          name: Default Admin Password
          description: Password for admin user
          optionType: ENVIRONMENT_VARIABLE
          defaultValue: 'password'
          valueType: PASSWORD
          required: true
          editable: true
  serviceRequirements: []
  serviceRepositories: []
  deploymentDefinition:
    deploymentType: DOCKER_COMPOSE
    composeFilename: docker-compose.yml
    dotEnvFile: ''
    envFilenames: []
